/groups/cellmap/cellmap/zouinkhim/process-blockwise/process_blockwise/predict_worker.py:205: RuntimeWarning: invalid value encountered in cast
  out_dataset[write_roi] = write_data[indexes[0]].astype(
Traceback (most recent call last):
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/tcp/tcp_stream.py", line 90, in _get_message
Traceback (most recent call last):
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/tcp/tcp_stream.py", line 90, in _get_message
    size = await self.stream.read_bytes(4)
    size = await self.stream.read_bytes(4)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/groups/cellmap/cellmap/zouinkhim/process-blockwise/process_blockwise/predict_worker.py", line 218, in <module>
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/groups/cellmap/cellmap/zouinkhim/process-blockwise/process_blockwise/predict_worker.py", line 218, in <module>
    cli()
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    cli()
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/click/core.py", line 1082, in main
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/cellmap/cellmap/zouinkhim/process-blockwise/process_blockwise/predict_worker.py", line 139, in start_worker
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/cellmap/cellmap/zouinkhim/process-blockwise/process_blockwise/predict_worker.py", line 139, in start_worker
    with client.acquire_block() as block:
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/contextlib.py", line 144, in __exit__
    with client.acquire_block() as block:
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
    next(self.gen)
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/client.py", line 101, in acquire_block
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/client.py", line 101, in acquire_block
    self.release_block(block)
    self.release_block(block)
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/client.py", line 111, in release_block
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/client.py", line 111, in release_block
    self.tcp_client.send_message(ReleaseBlock(block))
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/tcp/tcp_client.py", line 86, in send_message
    self.tcp_client.send_message(ReleaseBlock(block))
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/tcp/tcp_client.py", line 86, in send_message
    self._check_for_errors()
    self._check_for_errors()
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/tcp/tcp_client.py", line 119, in _check_for_errors
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/tcp/tcp_client.py", line 119, in _check_for_errors
    raise exception
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/tcp/tcp_client.py", line 142, in _receive
    raise exception
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/tcp/tcp_client.py", line 142, in _receive
    message = await self.stream._get_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/tcp/tcp_stream.py", line 98, in _get_message
    message = await self.stream._get_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/groups/scicompsoft/home/zouinkhim/miniconda3/envs/fly/lib/python3.11/site-packages/daisy/tcp/tcp_stream.py", line 98, in _get_message
    raise StreamClosedError(*self.address)
daisy.tcp.exceptions.StreamClosedError: ('10.36.60.13', 30715)
    raise StreamClosedError(*self.address)
daisy.tcp.exceptions.StreamClosedError: ('10.36.60.13', 30715)
